apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-Service
    app: demo-votingOs-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres
    app: demo-votingOs-app