apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-votingos-app
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: vottingos-app
    app: demo-votingos-app