apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: vottingos-app
    app: demo-votingos-app
spec:
  containers:
    - name: redis
      image: redis
      ports: 
        - containerPort: 6379