apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-Service
    app: demo-votingOs-app
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: result-app
    app: demo-votingOs-app